root: true
parser: ./build-lib/eslint/parser.js
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  jquery: true
  mocha: true
  es6: true
extends:
  - eslint:recommended
  - standard
  - standard-react
  - ./build-lib/eslint/eslint.config.js
plugins:
  - taskworld
  - react
  - import
  - pure
  - levitate
globals:
  expect: false
  _L: false
  __: false
rules:
  # Taskworld-specific rules
  taskworld/bem-no-bare-modifier: warn
  taskworld/bem-no-foreign-element: warn
  taskworld/no-reflux-listen-to: warn
  levitate/sort-imports: warn
  levitate/use-import-name-after-predefined-list: [ error, { moment: moment, _: lodash, classNames: classnames } ]

  # Our rules that can be fix automatically
  array-bracket-spacing: [ error, always ]
  comma-dangle: off
  jsx-quotes: [ error, prefer-single ]
  key-spacing: error
  keyword-spacing: error
  new-cap: [ error, { capIsNew: false } ]
  no-console: warn
  no-extra-parens: [ error, functions ]
  no-multi-spaces: [ error, { exceptions: { Property: false } } ]
  no-redeclare: [ error, { builtinGlobals: true } ]
  no-sequences: off
  no-trailing-spaces: off
  no-undef: error
  no-underscore-dangle: off
  no-unexpected-multiline: error
  no-unreachable: error
  no-unused-vars: [ error, { vars: all, args: none }]
  no-use-before-define: off
  object-curly-spacing: [ error, always ]
  padded-blocks: [ error, never ]
  prefer-const: warn
  quotes: [ error, single ]
  semi: [ error, never ]
  space-before-function-paren: [ error, always ]
  strict: off
  wrap-iife: [ error, inside ]

  # eslint-plugin-import rules
  import/named: error
  import/namespace: error

  # eslint-plugin-react rules
  react/jsx-boolean-value: [ error, never ]
  react/jsx-closing-bracket-location: [ warn, line-aligned ]
  react/jsx-indent-props: [ warn, 2 ]
  react/jsx-no-bind: off
  react/jsx-no-undef: error
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: error
  react/no-unknown-property: error
  react/prop-types: warn
  react/react-in-jsx-scope: error
  react/self-closing-comp: error
  react/sort-comp: [ error, {
    order: [
      "constructor",
      "lifecycle",
      "everything-else",
      "/^on.+$/",
      "/^render.+$/",
      "render"
    ]
  } ]

  # eslint-config-standard rules that cannot be fixed automatically yet
  # We turn them into warnings for now.
  brace-style: warn
  camelcase: warn
  comma-spacing: warn
  eqeqeq: warn
  handle-callback-err: warn
  indent: warn
  no-duplicate-imports: warn
  no-lone-blocks: warn
  no-new-wrappers: warn
  no-new: warn
  no-path-concat: warn
  no-return-assign: warn
  no-tabs: warn
  no-throw-literal: warn
  no-unneeded-ternary: warn
  no-useless-constructor: warn
  no-useless-escape: warn
  object-property-newline: warn
  one-var: warn
  operator-linebreak: warn
  react/jsx-indent: warn
  react/no-did-update-set-state: warn
  react/no-unused-prop-types: warn
